Repository CMU-313/spring24-nodebb-ccc, pull requests merged in 2024-02, with the labels that each got.

#14 Reactions
  pidfile 2
  pidfile 3
  public/language/en-US/topic.json
  public/openapi/read/topic/topic_id.yaml
  public/openapi/write.yaml
  public/openapi/write/posts/pid.yaml
  public/openapi/write/posts/pid/react.yaml
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  src/api/posts.js
  src/controllers/write/posts.js
  src/posts/data.js
  src/posts/index.js
  src/posts/reactions.js
  src/posts/votes.js
  src/routes/write/posts.js
  src/types/post.ts
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: enhancement

#15 Nodebb Dark mode Implementation
  public/src/client/topic/postTools.js
  public/src/client/topic/votes.js
  src/posts/votes.js
  themes/nodebb-theme-persona/less/style.less
  themes/nodebb-theme-persona/templates/header.tpl
Labels: enhancement

#19 Adding test cases for emoji reaction
  src/posts/reactions.js
  test/api.js
  test/posts.js
Labels: testing

#16 Reactions
  public/src/client/topic/postTools.js
  public/src/client/topic/votes.js
  src/posts/votes.js
  themes/nodebb-theme-persona/templates/partials/topic/post.tpl
Labels: removed artifacts

#20 Added UserGuide.md documentation
  UserGuide.md
Labels: documentation

#21 Wrote Asserts and Error Handling Cases
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  src/api/posts.js
  src/controllers/write/posts.js
  src/posts/reactions.js
Labels: testing

#22 Fixed an Abundance of Linter Errors Across Multiple Files
  public/src/client/topic/events.js
  public/src/client/topic/postTools.js
  src/api/posts.js
  src/categories/create.js
  src/controllers/write/posts.js
  src/posts/data.js
  src/posts/reactions.js
  src/posts/votes.js
  test/api.js
  test/posts.js
Labels: testing
